"use client";

export const REPORT_STYLES = {
  colors: {
    primary: "#0D47A1",
    success: "#2E7D32",
    warning: "#F57C00",
    danger: "#C62828",
    text: "#1a1a1a",
    muted: "#666666",
    tableAlt: "#F5F7FA",
  },
  container: {
    maxWidth: "210mm",
    width: "100%",
    margin: "0 auto",
    padding: "12px 16px",
    background: "white",
    fontFamily: "'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif",
    fontSize: "10px",
    lineHeight: "1.4",
    color: "#1a1a1a",
    overflowX: "hidden" as const,
  } as React.CSSProperties,
  card: {
    border: "1px solid #E0E0E0",
    borderRadius: "4px",
    padding: "12px",
    marginBottom: "8px",
  } as React.CSSProperties,
  tableCell: {
    border: "1px solid #E0E0E0",
    padding: "4px 8px",
    fontSize: "9px",
    wordBreak: "break-word" as const,
  } as React.CSSProperties,
  page: {
    maxWidth: "210mm",
    width: "100%",
    margin: "0 auto",
    padding: "12px 16px",
    background: "white",
    fontFamily: "'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif",
    fontSize: "10px",
    lineHeight: "1.4",
    color: "#1a1a1a",
    overflowX: "hidden" as const,
  } as React.CSSProperties,
  header: {
    background: "linear-gradient(135deg, #0D47A1 0%, #1565C0 100%)",
    color: "white",
    padding: "14px 18px",
    marginBottom: "8px",
    borderRadius: "4px",
  } as React.CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  } as React.CSSProperties,
  logo: {
    width: "55px",
    height: "55px",
    borderRadius: "50%",
    border: "2px solid white",
  } as React.CSSProperties,
  headerText: {
    flex: 1,
  } as React.CSSProperties,
  sectionTitle: {
    background: "#0D47A1",
    color: "white",
    padding: "5px 12px",
    fontSize: "11px",
    fontWeight: "800",
    letterSpacing: "0.5px",
    marginTop: "10px",
    marginBottom: "6px",
    borderRadius: "3px",
  } as React.CSSProperties,
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    marginBottom: "8px",
    fontSize: "9px",
    tableLayout: "fixed" as const,
  } as React.CSSProperties,
  th: {
    background: "#E3F2FD",
    border: "1px solid #BBDEFB",
    padding: "5px 8px",
    fontWeight: "700",
    fontSize: "9px",
    color: "#0D47A1",
    textAlign: "left" as const,
  } as React.CSSProperties,
  td: {
    border: "1px solid #E0E0E0",
    padding: "4px 8px",
    fontSize: "9px",
    wordBreak: "break-word" as const,
  } as React.CSSProperties,
  footer: {
    borderTop: "2px solid #0D47A1",
    paddingTop: "6px",
    marginTop: "12px",
    fontSize: "8px",
    color: "#666",
    display: "flex",
    justifyContent: "space-between" as const,
  } as React.CSSProperties,
};

export function ReportHeader({ logoUrl, title, subtitle, meta }: {
  logoUrl: string;
  title: string;
  subtitle?: string;
  meta?: { reportId?: string; generatedOn?: string; generatedAt?: string; generatedBy?: string; deptName?: string };
}) {
  return (
    <div style={REPORT_STYLES.header}>
      <div style={REPORT_STYLES.headerRow}>
        <img src={logoUrl} alt="JJCET" style={REPORT_STYLES.logo} />
        <div style={REPORT_STYLES.headerText}>
          <h1 style={{ margin: 0, fontSize: "16px", fontWeight: "800", letterSpacing: "0.5px" }}>J.J. College of Engineering & Technology</h1>
          <p style={{ margin: 0, fontSize: "9px", opacity: 0.9 }}>An Autonomous Institution | Tiruchirappalli – 621013</p>
          {subtitle && <p style={{ margin: 0, fontSize: "11px", fontWeight: "700", marginTop: "4px" }}>{subtitle}</p>}
        </div>
        {meta && (
          <div style={{ textAlign: "right", fontSize: "8px", lineHeight: "1.6" }}>
            {meta.reportId && <p style={{ margin: 0 }}>Report ID: {meta.reportId}</p>}
            {meta.deptName && <p style={{ margin: 0 }}>Dept: {meta.deptName}</p>}
            {meta.generatedOn && <p style={{ margin: 0 }}>Date: {meta.generatedOn}</p>}
            {meta.generatedAt && <p style={{ margin: 0 }}>Time: {meta.generatedAt}</p>}
          </div>
        )}
      </div>
    </div>
  );
}

export function SectionTitle({ num, title }: { num: number; title: string }) {
  return <div style={REPORT_STYLES.sectionTitle}>{num}. {title}</div>;
}

export function ReportFooter({ reportId, version }: { reportId?: string; version?: string }) {
  return (
    <div style={REPORT_STYLES.footer}>
      <span>Generated by JJCET NIRF ERP | Report {version || "v2.0"}</span>
      <span>Confidential – For Official Use Only</span>
      <span>www.jjcet.ac.in | 0431 – 2660566</span>
    </div>
  );
}

export function SignatureBox({ name, role }: { name: string; role: string }) {
  return (
    <div style={{ flex: 1, textAlign: "center", padding: "8px" }}>
      <div style={{ borderTop: "1px solid #333", marginTop: "40px", paddingTop: "4px" }}>
        <p style={{ margin: 0, fontSize: "10px", fontWeight: "700" }}>Signature</p>
        <p style={{ margin: 0, fontSize: "9px" }}>{name}</p>
        <p style={{ margin: 0, fontSize: "8px", color: "#666" }}>{role}</p>
        <p style={{ margin: 0, fontSize: "8px", color: "#666" }}>Date: ___/___/______</p>
        <p style={{ margin: 0, fontSize: "8px", color: "#666" }}>Seal:</p>
      </div>
    </div>
  );
}

export function QRPlaceholder({ id }: { id: string }) {
  return (
    <div style={{ width: "60px", height: "60px", border: "1px solid #ccc", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "7px", color: "#999", borderRadius: "4px" }}>
      QR: {id.slice(0, 8)}
    </div>
  );
}
