"use client";
import { useState, useEffect, useRef } from "react";
import { db } from "@/lib/firebase";
import { collection, getDocs, doc, setDoc, deleteDoc, query, orderBy, where } from "firebase/firestore";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { FileText, Plus, Eye, Send, Trash2, Download, Printer, Edit, Save, X } from "lucide-react";

const LOGO_URL = "/images/jjcet-logo.png";

const REPORT_TYPES = [
  { value: "staff", label: "Staff Reports" },
  { value: "department", label: "Department Reports" },
  { value: "semester", label: "Semester Reports" },
  { value: "annual", label: "Annual Reports" },
  { value: "nirf", label: "NIRF Reports" },
  { value: "naac", label: "NAAC Reports" },
  { value: "nba", label: "NBA Reports" },
  { value: "aicte", label: "AICTE Reports" },
];

const TEMPLATES: Record<string, string[]> = {
  staff: ["Publications", "Patents", "Research", "Events", "Monthly Progress", "Semester Progress", "Annual Performance", "Target Achievement", "Pending Activities"],
  department: ["Complete Report", "Faculty Performance", "Department Publications", "Department Patents", "Student Achievements", "Placement Statistics", "Target vs Achievement", "Monthly Report", "Annual Report"],
  semester: ["Semester Summary", "Faculty Load", "Student Performance", "Research Output"],
  annual: ["Annual Report", "Department Comparison", "Institutional Summary"],
  nirf: ["NIRF Submission Report", "NIRF Parameter Analysis"],
  naac: ["NAAC SSR Report", "NAAC Criterion Analysis"],
  nba: ["NBA Accreditation Report"],
  aicte: ["AICTE Annual Report"],
};

function genId() {
  return "rpt-" + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export default function ReportsPage() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showGenerate, setShowGenerate] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [showViewer, setShowViewer] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editForm, setEditForm] = useState<any>(null);
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [form, setForm] = useState({ title: "", type: "staff", category: "", academicYear: "2024-25", content: "" });
  const reportPrintRef = useRef<HTMLDivElement>(null);

  const user = typeof window !== "undefined" ? JSON.parse(localStorage.getItem("user") || "null") : null;

  const loadReports = async () => {
    try {
      const snap = await getDocs(query(collection(db, "reports"), orderBy("createdAt", "desc")));
      setReports(snap.docs.map(d => ({ id: d.id, ...d.data() })));
    } catch (e) { console.error("Load reports error:", e); }
    setLoading(false);
  };

  useEffect(() => { loadReports(); }, []);

  const generateReport = async () => {
    setGenerating(true);
    try {
      const id = genId();
      const now = new Date().toISOString();
      const data = {
        title: form.title,
        type: form.type,
        category: form.category,
        academicYear: form.academicYear,
        content: form.content || `Report: ${form.title}\nType: ${form.type}\nCategory: ${form.category}\nAcademic Year: ${form.academicYear}\n\nGenerated by: ${user?.name || "Unknown"}\nDepartment: ${user?.departmentId || "All"}\nDate: ${now}`,
        status: "DRAFT",
        currentLevel: "STAFF",
        creatorId: user?.id || "1",
        departmentId: user?.departmentId || null,
        createdAt: now,
        updatedAt: now,
      };
      await setDoc(doc(db, "reports", id), data);
      setShowGenerate(false);
      setForm({ title: "", type: "staff", category: "", academicYear: "2024-25", content: "" });
      loadReports();
    } catch (e) { console.error("Generate report error:", e); alert("Error generating report: " + (e as Error).message); }
    setGenerating(false);
  };

  const submitReport = async (id: string) => {
    try {
      await setDoc(doc(db, "reports", id), { status: "SUBMITTED", submittedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }, { merge: true });
      loadReports();
    } catch (e) { console.error("Submit error:", e); }
  };

  const deleteReport = async (id: string) => {
    if (!confirm("Delete this report?")) return;
    try {
      await deleteDoc(doc(db, "reports", id));
      loadReports();
    } catch (e) { console.error("Delete error:", e); }
  };

  const viewReport = (r: any) => {
    setSelectedReport(r);
    setEditForm({ ...r });
    setIsEditing(false);
    setShowViewer(true);
  };

  const startEdit = () => {
    setEditForm({ ...selectedReport });
    setIsEditing(true);
  };

  const cancelEdit = () => {
    setEditForm({ ...selectedReport });
    setIsEditing(false);
  };

  const saveEdit = async () => {
    if (!editForm) return;
    try {
      await setDoc(doc(db, "reports", editForm.id), {
        title: editForm.title,
        type: editForm.type,
        category: editForm.category,
        academicYear: editForm.academicYear,
        content: editForm.content,
        updatedAt: new Date().toISOString(),
      }, { merge: true });
      setSelectedReport(editForm);
      setIsEditing(false);
      loadReports();
    } catch (e) {
      console.error("Save edit error:", e);
      alert("Error saving changes: " + (e as Error).message);
    }
  };

  const printReport = () => {
    const el = reportPrintRef.current;
    if (!el) return;
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>${selectedReport?.title || "Report"}</title>
<style>
@page{size:A3 portrait;margin:5mm;}
*{margin:0;padding:0;box-sizing:border-box;}
body{font-family:Arial,Helvetica,sans-serif;font-size:9px;line-height:1.3;color:#1a1a1a;-webkit-print-color-adjust:exact;print-color-adjust:exact;}
.header{background:linear-gradient(135deg,#1e3a8a,#2563eb);color:white;padding:12px 20px;display:flex;align-items:center;gap:15px;}
.header img{width:80px;height:80px;border-radius:50%;background:white;padding:4px;object-fit:contain;}
.header-center{text-align:center;flex:1;}
.header-center h1{font-size:24px;letter-spacing:4px;font-weight:900;margin-bottom:2px;}
.header-center p{font-size:14px;letter-spacing:2px;color:#bfdbfe;}
.header-center .autonomous{font-size:13px;color:#fbbf24;font-weight:bold;margin:2px 0;}
.header-center .group{background:#f97316;color:white;display:inline-block;padding:2px 14px;border-radius:3px;font-size:10px;font-weight:bold;}
.header-right{text-align:right;font-size:8px;color:#bfdbfe;}
.report-title-bar{background:#1e3a8a;color:white;padding:6px 15px;font-size:12px;font-weight:bold;letter-spacing:1px;text-align:center;}
.meta-table{width:100%;border-collapse:collapse;margin:10px 0;}
.meta-table td{padding:4px 10px;border:1px solid #e2e8f0;font-size:9px;}
.meta-table td:first-child{background:#e2e8f0;font-weight:bold;width:120px;}
.content-area{padding:12px 15px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:4px;margin:10px 0;min-height:200px;}
.content-area h3{color:#1e3a8a;margin-bottom:8px;font-size:11px;border-bottom:2px solid #1e3a8a;padding-bottom:4px;}
.content-text{font-size:9px;line-height:1.6;white-space:pre-wrap;}
.status-badge{display:inline-block;padding:2px 8px;border-radius:3px;font-size:8px;font-weight:bold;}
.status-draft{background:#fef3c7;color:#92400e;}
.status-submitted{background:#dbeafe;color:#1e40af;}
.status-approved{background:#dcfce7;color:#166534;}
.status-locked{background:#fee2e2;color:#991b1b;}
.signature-section{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:0;margin-top:15px;}
.sig-block{text-align:center;padding:8px;border:1px solid #e2e8f0;background:#f8fafc;}
.sig-block .title{background:#1e3a8a;color:white;padding:4px 8px;font-size:8px;font-weight:bold;margin:-8px -8px 8px -8px;}
.sig-block .role{font-weight:bold;font-size:9px;margin-top:5px;}
.sig-block .name{font-size:8px;color:#666;}
.sig-line{border-bottom:1px dashed #999;height:30px;margin:8px 0;}
.footer{background:#1e3a8a;color:white;padding:8px 20px;display:flex;justify-content:space-between;align-items:center;font-size:8px;margin-top:15px;}
@media print{body{margin:0;padding:0;}}
</style></head><body>` + el.innerHTML + `</body></html>`);
    w.document.close();
    setTimeout(() => w.print(), 300);
  };

  const downloadCSV = () => {
    if (!reports.length) return;
    const csv = ["Title,Type,Category,Status,Academic Year,Created"].concat(
      reports.map(r => `"${r.title}","${r.type}","${r.category}","${r.status}","${r.academicYear || ""}","${r.createdAt}"`)
    ).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "reports.csv";
    a.click();
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div><h1 className="text-2xl font-bold">Reports</h1><p className="text-muted-foreground">Generate, manage, and submit reports</p></div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={downloadCSV}><Download className="h-4 w-4 mr-2" />Export CSV</Button>
            <Button onClick={() => setShowGenerate(true)}><Plus className="h-4 w-4 mr-2" />Generate Report</Button>
          </div>
        </div>

        {loading ? <p className="text-muted-foreground">Loading...</p> : reports.length === 0 ? (
          <Card><CardContent className="py-12 text-center text-muted-foreground"><FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />No reports generated yet. Click &quot;Generate Report&quot; to create one.</CardContent></Card>
        ) : (
          <Card>
            <CardContent className="p-0">
              <table className="w-full text-sm">
                <thead><tr className="border-b"><th className="p-4 text-left">Title</th><th className="p-4 text-left">Type</th><th className="p-4 text-left">Category</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">Level</th><th className="p-4 text-right">Actions</th></tr></thead>
                <tbody>{reports.map((r) => (
                  <tr key={r.id} className="border-b hover:bg-muted/50">
                    <td className="p-4 font-medium">{r.title}</td>
                    <td className="p-4"><Badge variant="secondary">{r.type}</Badge></td>
                    <td className="p-4">{r.category?.replace(/_/g, " ")}</td>
                    <td className="p-4"><Badge variant={r.status === "LOCKED" ? "default" : r.status === "SUBMITTED" ? "secondary" : "outline"}>{r.status}</Badge></td>
                    <td className="p-4">{r.currentLevel}</td>
                    <td className="p-4 text-right">
                      <div className="flex gap-1 justify-end">
                        <Button size="sm" variant="ghost" onClick={() => viewReport(r)}><Eye className="h-4 w-4" /></Button>
                        {r.status === "DRAFT" && <Button size="sm" variant="ghost" onClick={() => submitReport(r.id)}><Send className="h-4 w-4" /></Button>}
                        {r.status === "DRAFT" && <Button size="sm" variant="ghost" onClick={() => deleteReport(r.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button>}
                      </div>
                    </td>
                  </tr>
                ))}</tbody>
              </table>
            </CardContent>
          </Card>
        )}

        <Dialog open={showGenerate} onOpenChange={setShowGenerate}>
          <DialogContent>
            <DialogHeader><DialogTitle>Generate New Report</DialogTitle></DialogHeader>
            <div className="space-y-4 mt-4">
              <div><Label>Report Title</Label><Input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. IT Department Annual Report 2024-25" /></div>
              <div><Label>Report Type</Label>
                <select className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value, category: "" })}>
                  {REPORT_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
                </select>
              </div>
              <div><Label>Category</Label>
                <select className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>
                  <option value="">Select category</option>
                  {(TEMPLATES[form.type] || []).map(t => <option key={t} value={t.toLowerCase().replace(/\s+/g, "_")}>{t}</option>)}
                </select>
              </div>
              <div><Label>Academic Year</Label><Input value={form.academicYear} onChange={(e) => setForm({ ...form, academicYear: e.target.value })} /></div>
              <div><Label>Content / Notes</Label><textarea className="w-full h-32 rounded-md border border-input bg-background px-3 py-2 text-sm" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="Add report content or notes..." /></div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowGenerate(false)}>Cancel</Button>
              <Button onClick={generateReport} disabled={!form.title || !form.category || generating}>
                {generating ? "Generating..." : "Generate"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <Dialog open={showViewer} onOpenChange={setShowViewer}>
          <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <div className="flex items-center justify-between">
                <DialogTitle>{isEditing ? "Edit Report" : selectedReport?.title}</DialogTitle>
                <div className="flex gap-2">
                  {!isEditing ? (
                    <>
                      <Button size="sm" variant="outline" onClick={startEdit}><Edit className="h-4 w-4 mr-1" />Edit</Button>
                      <Button size="sm" onClick={printReport}><Printer className="h-4 w-4 mr-1" />Print / PDF</Button>
                    </>
                  ) : (
                    <>
                      <Button size="sm" variant="outline" onClick={cancelEdit}><X className="h-4 w-4 mr-1" />Cancel</Button>
                      <Button size="sm" onClick={saveEdit}><Save className="h-4 w-4 mr-1" />Save Changes</Button>
                    </>
                  )}
                </div>
              </div>
            </DialogHeader>
            {selectedReport && (
              <div className="space-y-4">
                {isEditing ? (
                  <div className="space-y-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                    <p className="text-sm text-blue-700 font-medium">Edit report fields below, then save or print.</p>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <Label className="text-xs">Report Title</Label>
                        <Input value={editForm?.title || ""} onChange={(e) => setEditForm({ ...editForm, title: e.target.value })} />
                      </div>
                      <div>
                        <Label className="text-xs">Report Type</Label>
                        <select className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={editForm?.type || ""} onChange={(e) => setEditForm({ ...editForm, type: e.target.value })}>
                          {REPORT_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
                        </select>
                      </div>
                      <div>
                        <Label className="text-xs">Category</Label>
                        <Input value={editForm?.category || ""} onChange={(e) => setEditForm({ ...editForm, category: e.target.value })} />
                      </div>
                      <div>
                        <Label className="text-xs">Academic Year</Label>
                        <Input value={editForm?.academicYear || ""} onChange={(e) => setEditForm({ ...editForm, academicYear: e.target.value })} />
                      </div>
                    </div>
                    <div>
                      <Label className="text-xs">Report Content</Label>
                      <textarea className="w-full h-48 rounded-md border border-input bg-background px-3 py-2 text-sm font-mono" value={editForm?.content || ""} onChange={(e) => setEditForm({ ...editForm, content: e.target.value })} placeholder="Enter report content..." />
                    </div>
                  </div>
                ) : (
                  <div className="p-4 bg-muted rounded-lg">
                    <div className="flex gap-4 text-sm text-muted-foreground mb-3">
                      <span>Type: <Badge variant="secondary">{selectedReport.type}</Badge></span>
                      <span>Status: <Badge>{selectedReport.status}</Badge></span>
                      <span>Level: {selectedReport.currentLevel}</span>
                      <span>Year: {selectedReport.academicYear}</span>
                    </div>
                    <pre className="whitespace-pre-wrap font-sans text-sm">{selectedReport.content || "No content"}</pre>
                  </div>
                )}

                <div ref={reportPrintRef}>
                  <div style={{ padding: 0, maxWidth: "100%", overflow: "hidden" }}>
                    <div style={{ background: "linear-gradient(135deg, #1e3a8a, #2563eb)", color: "white", padding: "12px 20px", display: "flex", alignItems: "center", gap: "15px" }}>
                      <img src={LOGO_URL} alt="JJCET" style={{ width: "80px", height: "80px", borderRadius: "50%", background: "white", padding: "4px", objectFit: "contain" }} />
                      <div style={{ flex: 1, textAlign: "center" }}>
                        <h1 style={{ fontSize: "24px", letterSpacing: "4px", fontWeight: "900", marginBottom: "2px" }}>J.J. COLLEGE</h1>
                        <p style={{ fontSize: "14px", letterSpacing: "2px", color: "#bfdbfe" }}>ENGINEERING AND TECHNOLOGY</p>
                        <p style={{ fontSize: "13px", color: "#fbbf24", fontWeight: "bold", margin: "2px 0" }}>AUTONOMOUS</p>
                        <span style={{ background: "#f97316", color: "white", padding: "2px 14px", borderRadius: "3px", fontSize: "10px", fontWeight: "bold" }}>SOWDAMBIKAA GROUP OF INSTITUTIONS</span>
                      </div>
                      <div style={{ textAlign: "right", fontSize: "8px", color: "#bfdbfe" }}>
                        <p>Report ID: {isEditing ? editForm?.id : selectedReport?.id}</p>
                        <p>Academic Year: {isEditing ? editForm?.academicYear : selectedReport?.academicYear}</p>
                        <p>Generated: {new Date().toLocaleDateString("en-IN")}</p>
                      </div>
                    </div>

                    <div style={{ background: "#1e3a8a", color: "white", padding: "6px 15px", fontSize: "12px", fontWeight: "bold", letterSpacing: "1px", textAlign: "center" }}>
                      {(isEditing ? editForm?.title : selectedReport?.title) || "OFFICIAL REPORT"} – {(isEditing ? editForm?.academicYear : selectedReport?.academicYear) || "2024-25"}
                    </div>

                    <table className="meta-table" style={{ width: "100%", borderCollapse: "collapse", margin: "10px 0" }}>
                      <tbody>
                        <tr>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold", width: "120px" }}>Report Title</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{isEditing ? editForm?.title : selectedReport?.title}</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold", width: "120px" }}>Report Type</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{isEditing ? editForm?.type : selectedReport?.type}</td>
                        </tr>
                        <tr>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Category</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{(isEditing ? editForm?.category : selectedReport?.category)?.replace(/_/g, " ")}</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Status</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>
                            <span style={{ display: "inline-block", padding: "2px 8px", borderRadius: "3px", fontSize: "8px", fontWeight: "bold", background: (isEditing ? editForm?.status : selectedReport?.status) === "DRAFT" ? "#fef3c7" : (isEditing ? editForm?.status : selectedReport?.status) === "SUBMITTED" ? "#dbeafe" : "#dcfce7", color: (isEditing ? editForm?.status : selectedReport?.status) === "DRAFT" ? "#92400e" : (isEditing ? editForm?.status : selectedReport?.status) === "SUBMITTED" ? "#1e40af" : "#166534" }}>
                              {isEditing ? editForm?.status : selectedReport?.status}
                            </span>
                          </td>
                        </tr>
                        <tr>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Department</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{isEditing ? editForm?.departmentId : selectedReport?.departmentId}</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Generated By</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{user?.name || "System"}</td>
                        </tr>
                        <tr>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Date Created</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{isEditing ? editForm?.createdAt : selectedReport?.createdAt}</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px", background: "#e2e8f0", fontWeight: "bold" }}>Last Updated</td>
                          <td style={{ padding: "4px 10px", border: "1px solid #e2e8f0", fontSize: "9px" }}>{isEditing ? editForm?.updatedAt : selectedReport?.updatedAt}</td>
                        </tr>
                      </tbody>
                    </table>

                    <div style={{ padding: "12px 15px", background: "#f8fafc", border: "1px solid #e2e8f0", borderRadius: "4px", margin: "10px 0", minHeight: "200px" }}>
                      <h3 style={{ color: "#1e3a8a", marginBottom: "8px", fontSize: "11px", borderBottom: "2px solid #1e3a8a", paddingBottom: "4px" }}>Report Content</h3>
                      <div style={{ fontSize: "9px", lineHeight: "1.6", whiteSpace: "pre-wrap" }}>{isEditing ? editForm?.content : selectedReport?.content || "No content available."}</div>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: "0", marginTop: "15px" }}>
                      {[
                        { title: "PREPARED BY", role: "Staff", name: user?.name || "Staff Member" },
                        { title: "VERIFIED BY", role: "HOD", name: "Dr. A. HOD Name" },
                        { title: "VERIFIED BY", role: "Vice Principal", name: "Dr. B. Vice Principal" },
                        { title: "APPROVED BY", role: "Principal", name: "Dr. C. Principal" },
                      ].map((s, i) => (
                        <div key={i} style={{ textAlign: "center", padding: "8px", border: "1px solid #e2e8f0", background: "#f8fafc" }}>
                          <div style={{ background: "#1e3a8a", color: "white", padding: "4px 8px", fontSize: "8px", fontWeight: "bold", margin: "-8px -8px 8px -8px" }}>{s.title}</div>
                          <div style={{ borderBottom: "1px dashed #999", height: "30px", margin: "8px 0" }} />
                          <p style={{ fontWeight: "bold", fontSize: "9px", marginTop: "5px" }}>{s.role}</p>
                          <p style={{ fontSize: "8px", color: "#666" }}>{s.name}</p>
                          <p style={{ fontSize: "7px", color: "#999", marginTop: "2px" }}>Date: {new Date().toLocaleDateString("en-IN")}</p>
                        </div>
                      ))}
                    </div>

                    <div style={{ background: "#1e3a8a", color: "white", padding: "8px 20px", display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: "8px", marginTop: "15px" }}>
                      <span>Pudukottai Main Road, Puliampatti, Trichy – 620 009, Tamil Nadu, India.</span>
                      <span>0431 – 2660566</span>
                      <span>www.jjcet.ac.in</span>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </DashboardLayout>
  );
}
